parameters:
#    ruudy_metronic.example.class: Ruudy\MetronicBundle\Example

services:
#    ruudy_metronic.example:
#        class: %ruudy_metronic.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]